/**
 * Copyright (c) 2020-present, Goldman Sachs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum INTERACTIVE_APPLICATION_HASH_STRUCTURE {
  INTERACTIVE_APPLICATION = 'INTERACTIVE_APPLICATION',

  INTERACTIVE_APPLICATION_STORE_RELATIONAL = 'INTERACTIVE_APPLICATION_STORE_RELATIONAL',

  INTERACTIVE_AUTHORIZATION_DEFAULT = 'INTERACTIVE_AUTHORIZATION_DEFAULT',

  INTERACTIVE_TYPE_CONFIGURATION_PRIMARY_KEYS = 'INTERACTIVE_TYPE_CONFIGURATION_PRIMARY_KEYS',
  INTERACTIVE_TYPE_CONFIGURATION_PRIMARY_KEYS_PRIMARY_KEY = 'INTERACTIVE_TYPE_CONFIGURATION_PRIMARY_KEYS_PRIMARY_KEY',
  INTERACTIVE_TYPE_CONFIGURATION_STRING_LENGTH = 'INTERACTIVE_TYPE_CONFIGURATION_STRING_LENGTH',

  INTERACTIVE_SERVICE_READ = 'INTERACTIVE_SERVICE_READ',
  INTERACTIVE_SERVICE_CREATE = 'INTERACTIVE_SERVICE_CREATE',
  INTERACTIVE_SERVICE_UPDATE = 'INTERACTIVE_SERVICE_UPDATE',
  INTERACTIVE_SERVICE_UPSERT = 'INTERACTIVE_SERVICE_UPSERT',
  INTERACTIVE_SERVICE_DELETE = 'INTERACTIVE_SERVICE_DELETE',
}
